import { Button } from '../ui/Button'
import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { scanOpportunity, readScan, type OpportunityRequest, type OpportunityScan, type Mode } from '../services/workspace'
import { ApiError } from '../services/api'
import { RouteComparison } from './RouteComparison'
import { parseRoute } from '../services/routing'
import { SafetyNotice } from './WorkspaceViews'
const value = (v: string | number | null | undefined) => v ?? 'Unavailable'
export function OpportunityView({ mode, sandbox, scanId }: { mode: Mode; sandbox: boolean; scanId?: string }) {
  const [budget,setBudget]=useState(''),[risk,setRisk]=useState(''),[window,setWindow]=useState<'PRE_OPEN'|'BEFORE_MONDAY'>('PRE_OPEN'),[tickers,setTickers]=useState(''),[scenario,setScenario]=useState('')
  const [scan,setScan]=useState<OpportunityScan|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const pending=useRef<AbortController|null>(null), attempt=useRef<{body:OpportunityRequest; digest:string}|null>(null), locked=useRef(false)
  const saved=useQuery({queryKey:['opportunity-scan',mode,scanId],queryFn:({signal})=>readScan(scanId!,mode,signal),enabled:!!scanId,retry:false,refetchOnWindowFocus:false})
  useEffect(()=>()=>{pending.current?.abort();pending.current=null},[])
  async function submit(event:React.FormEvent){
    event.preventDefault();if(locked.current||scan)return
    const input={budget_usd:budget,risk_budget_usd:risk,time_window:window,universe:{tickers:tickers?tickers.split(',').map(t=>t.trim().toUpperCase()):[]},...(sandbox&&scenario?{demo_scenario:scenario as 'steady'|'thin-move'|'supported-move'}:{})}
    const digest=JSON.stringify(input)
    if(!attempt.current||attempt.current.digest!==digest)attempt.current={digest,body:{...input,correlation_id:crypto.randomUUID()}}
    const controller=new AbortController();pending.current=controller;locked.current=true
    setBusy(true);setError('');setScan(null);setSelected('')
    try{const result=await scanOpportunity(attempt.current.body,mode,controller.signal);if(pending.current===controller&&!controller.signal.aborted)setScan(result)}
    catch(e){if(pending.current===controller&&!controller.signal.aborted)setError(e instanceof ApiError?e.message+' Retry unchanged inputs with the retained scan identity.':'Scan input or backend evidence could not be verified.')}
    finally{locked.current=false;if(pending.current===controller&&!controller.signal.aborted)setBusy(false)}
  }
  const result=scanId?saved.isError||saved.isFetching?null:saved.data:scan
  const detail=result?.candidates.find(c=>c.candidate.candidate_id===selected)
  return <section className="workspace-view" aria-label="Opportunity analysis"><h1>Find Opportunity</h1><SafetyNotice mode={mode}/><p>Analytical scans only. Production OPPORTUNITY_GATE remains BLOCKED_BY_TRUST. A BUY proposal is not a completed trade.</p>
    {!scanId&&<form className="workspace-form" onSubmit={e=>void submit(e)}><label>Investment amount / USD notional<input value={budget} required maxLength={37} inputMode="decimal" disabled={busy} onChange={e=>{setBudget(e.target.value);setScan(null)}}/></label><label>Risk budget / USD<input value={risk} required maxLength={37} inputMode="decimal" disabled={busy} onChange={e=>{setRisk(e.target.value);setScan(null)}}/></label><label>Market window<select value={window} disabled={busy} onChange={e=>{setWindow(e.target.value as typeof window);setScan(null)}}><option value="PRE_OPEN">Before US open</option><option value="BEFORE_MONDAY">Before Monday open</option></select></label><label>Optional ticker universe<input value={tickers} maxLength={1500} disabled={busy} onChange={e=>{setTickers(e.target.value);setScan(null)}} placeholder="Comma-separated; empty discovers all"/></label>{sandbox&&<label>Explicit synthetic scenario<select value={scenario} disabled={busy} onChange={e=>{setScenario(e.target.value);setScan(null)}}><option value="">Ordinary discovered data</option><option value="steady">NORMAL</option><option value="thin-move">LIKELY NOISE</option><option value="supported-move">LIKELY INFORMATION</option></select></label>}<Button disabled={busy||!!scan} className="refresh-button">{busy?'Scanning…':'Scan opportunities'}</Button><p>Risk budget is ex-ante, not a guaranteed maximum realized loss. No automatic resubmission or full-budget investment. Change inputs to request a new scan after a completed result.</p></form>}
    {(busy||saved.isFetching)&&<p role="status">Loading deterministic opportunity evidence…</p>}{(error||saved.isError)&&<p role="alert">{error||'Stored scan unavailable. No candidate was substituted.'}</p>}
    {result&&<><section className="panel"><h2>{result.final_action}</h2><p>Universe {result.universe_count} · Eligible {result.eligible_count} · Rejected {result.rejected_count} · Top-K {result.top_k.length} · Risk {result.risk_validation}</p><p>Historical scan snapshot as of {result.timestamp} · Decision {result.decision_id} · {result.blockers.join(' · ')}</p><p>Selected stock: {result.selected_candidate?.ticker??'None — stand down'} · {result.no_broadcast_statement}</p>{!result.candidates.length&&<p>No discovered candidates. Provider or evidence availability is recorded in the blockers.</p>}
      <div className="comparison-scroll" tabIndex={0} role="region" aria-label="Opportunity candidates"><table><caption>Deterministic backend candidate ranking</caption><thead><tr><th>Rank</th><th>Stock / issuer</th><th>Trust / confidence</th><th>Liquidity USD</th><th>Effective cost USD/share</th><th>Predicted opening move</th><th>Net edge USD</th><th>Decision</th></tr></thead><tbody>{result.candidates.map(row=><tr key={row.candidate.candidate_id}><td>{row.rank??'Rejected'}</td><td>{row.candidate.ticker} / {row.candidate.issuer}</td><td>{row.candidate.trust} / {value(row.candidate.confidence)}</td><td>{value(row.candidate.liquidity_usd)}</td><td>{value(row.candidate.effective_cost)}</td><td>{value(row.candidate.predicted_open_return)}</td><td>{value(row.candidate.net_edge_usd)}</td><td>{row.candidate.eligibility} · {row.rejection_reasons.join(' · ')}<Button className="refresh-button" onClick={()=>setSelected(row.candidate.candidate_id)}>Inspect {row.candidate.ticker} evidence</Button></td></tr>)}</tbody></table></div>
      <a className="refresh-button" href={`#audit/${encodeURIComponent(result.decision_id)}`}>Inspect opportunity audit</a><a href={`#opportunity/${result.run_id}`} className="refresh-button">Open persisted scan</a></section>
      {detail&&<section className="panel" aria-label="Opportunity detail"><h2>Opportunity detail — {detail.candidate.ticker}</h2><p>Issuer {detail.candidate.issuer} · Token {value(detail.candidate.token)} · Trust {detail.candidate.trust} · {value(detail.candidate.confidence)}</p><p>{detail.rejection_reasons.join(' · ')||'Deterministic candidate eligible; proposal only'}</p><dl className="trust-facts">{Object.entries({deviation:detail.candidate.deviation,volume_percentile:detail.candidate.volume_percentile,liquidity_state:detail.candidate.liquidity_state,news_state:detail.candidate.news_state,historical_pattern:detail.candidate.historical_pattern,analogue_count:detail.candidate.analogue_count,prediction_status:detail.candidate.prediction_status,predicted_open_return:detail.candidate.predicted_open_return,prediction_samples:detail.candidate.prediction_samples,baseline_samples:detail.candidate.baseline_samples,fees_usd:detail.candidate.fees_usd,gas_usd:detail.candidate.gas_usd,slippage_usd:detail.candidate.estimated_slippage_usd,net_edge_usd:detail.candidate.net_edge_usd,proposed_notional_usd:detail.candidate.proposed_notional_usd,stress_loss_usd:detail.candidate.stress_loss_usd}).map(([name,v])=><div key={name}><dt>{name.replaceAll('_',' ')}</dt><dd>{value(v)}</dd></div>)}</dl><p>Evidence basis: {detail.candidate.economics_basis}. Research/agent interpretation does not override hard rules. Simulation: unavailable for this scan. Approval/execution: blocked.</p><p>Observed {detail.candidate.observed_at} · Available {detail.candidate.available_at}</p><p>Evidence references: {detail.candidate.evidence_refs.join(' · ')||'Unavailable'}</p>{detail.route&&<RouteComparison route={parseRoute(detail.route,mode==='DEMO'?'DEMO':'LIVE',detail.candidate.ticker,undefined,detail.route.policy.purpose)} expired/>}</section>}
      <section className="panel"><h2>Evidence / decision provenance</h2>{result.provenance.map(p=><p key={p.evidence_id}>{p.source} · Observed {p.observed_at} · Available {p.available_at} · {p.evidence_id}</p>)}<p>Agent interpretation: {result.agent_run?.status??'NOT_RUN'} · Final action {result.final_action}. Raw agent responses and hidden reasoning are not displayed.</p>{result.agent_run&&<p>Validated decision reasons: {(result.agent_run.decision.reasons??[]).join(' · ')}</p>}</section>
    </>}
  </section>
}
