"""Generate Phase 15 display contracts from authoritative Pydantic wire schemas.

No application state/provider reads. --check detects backend/frontend schema drift.
"""

import argparse
import json
from pathlib import Path

from app.api.workspace import WorkspaceState
from app.models.display_history import DisplayHistory
from app.models.opportunity_scan import OpportunityRequest, OpportunityScan
from app.models.portfolio import ConfigRequest, PortfolioConfig, RebalancePlan
from app.models.presentation import PresentationAnalysis, PresentationScan, PresentationWorkspace
from app.models.routing import RouteDecision
from app.models.scorecard import AuditPage

ROOT = Path(__file__).resolve().parents[1]
MODELS = (
    DisplayHistory,
    WorkspaceState,
    OpportunityScan,
    OpportunityRequest,
    ConfigRequest,
    RebalancePlan,
    PortfolioConfig,
    AuditPage,
    PresentationWorkspace,
    PresentationAnalysis,
    PresentationScan,
    RouteDecision,
)


def schemas():
    return {
        model.__name__: model.model_json_schema(
            mode="validation" if model in (ConfigRequest, OpportunityRequest) else "serialization"
        )
        for model in MODELS
    }


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    for keyword in ("anyOf", "oneOf"):
        if keyword in schema:
            return "(" + " | ".join(ts_type(v) for v in schema[keyword]) + ")"
    kind = schema.get("type")
    if kind == "array":
        return "(" + ts_type(schema.get("items", {})) + ")[]"
    if kind == "object":
        required = set(schema.get("required", ()))
        fields = [
            json.dumps(k) + ("" if k in required else "?") + ": " + ts_type(v)
            for k, v in schema.get("properties", {}).items()
        ]
        extra = schema.get("additionalProperties")
        if "patternProperties" in schema:
            fields.append(
                "[key: string]: "
                + " | ".join(ts_type(v) for v in schema["patternProperties"].values())
            )
        if isinstance(extra, dict):
            fields.append("[key: string]: " + ts_type(extra))
        elif extra is True:
            fields.append("[key: string]: unknown")
        return "{ " + "; ".join(fields) + " }"
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def artifacts():
    wire = schemas()
    # Namespace each root so input/serialization definitions never overwrite each other.
    lines = [
        "// Generated by scripts/generate-ui-contracts.py. Do not edit financial contracts here."
    ]
    for root, schema in wire.items():
        namespace = json.loads(json.dumps(schema).replace("#/$defs/", f"#/$defs/{root}_"))
        for name, definition in namespace.get("$defs", {}).items():
            lines.append(f"export type {root}_{name} = {ts_type(definition)}")
        lines.append(f"export type {root} = {ts_type(namespace)}")
    return {
        ROOT / "frontend/src/types/backend.generated.ts": "\n".join(lines) + "\n",
        ROOT / "frontend/src/services/backendSchemas.json": json.dumps(wire, separators=(",", ":"))
        + "\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    for path, content in artifacts().items():
        if options.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit("Frontend contracts differ from backend schemas")
        else:
            path.write_text(content)
    print(f"PASS: {len(MODELS)} Pydantic-derived frontend contracts")


if __name__ == "__main__":
    main()
