from typing import Protocol

from app.models.data import EquityObservation, Issuer, NewsEvent, TokenMetadata


class RWADataProvider(Protocol):
    def platforms(self) -> list[Issuer]: ...
    def search(self, keyword: str): ...
    def tokens(self, chain: str = "56") -> list[TokenMetadata]: ...
    def profile(self, token: TokenMetadata) -> TokenMetadata: ...
    def observation(self, token: TokenMetadata): ...


class EquityDataProvider(Protocol):
    def get_snapshot(self, ticker: str) -> EquityObservation: ...
    def get_latest_quote(self, ticker: str) -> EquityObservation: ...
    def get_historical_bars(self, ticker: str, start: str, end: str, **kwargs): ...
    def get_market_status(self): ...
    def get_market_holidays(self): ...
    def get_previous_regular_close(self, ticker: str, at, calendar): ...
    def get_corporate_actions(self, ticker: str): ...


class NewsProvider(Protocol):
    def get_news(self, ticker: str, **kwargs) -> list[NewsEvent]: ...


class CalendarProvider(Protocol):
    def status(self, at): ...
    def session(self, day): ...
    def previous_session(self, at): ...
